### ISSUE TITLE
High interest

### ISSUE THREAD

**Issue by j0el** [mmtang/swamp-data-dashboard#4]
Michelle,
I am a volunteer with the Channel Islands neighborhood council and we collect and analyze water quality in our harbor.  Our data is submitted through CEDEN and I am very interested in this dashboard.  If I can be of any use in testing this app or in any other way, please let me know.  

Best regards,
Joel Berman  joel.berman@gmail.com

**Comment by mmtang** [comment]
Hi Joel, thanks for your interest in this project! We could definitely use some help with testing. I'll keep you in mind as we get ready to roll out the latest version. Also, do let me know if there's anything in particular that are interested in helping out with.

**Comment by j0el** [comment]
Hi Michelle,
I am a 75 year old retiree.  My work experience has always been in
computers. I am ok in python, javascript, css, html, express, ..but they
are not my strengths.  Without boring you our harbor is controlled by
city/county and special districts.  Agricultural and storm drain runoff has
been a problem and since 2018.  We used to have a power plant at the end of
our canal that pumped millions of gallons of seawater which did a good job
of flushing out the harbor, but that is shut down now.  Between the
nutrients from the agriculture which causes growth that reduces the oxygen
in the water, and the storm drains which load the harbor with bacteria, we
need mitigation but it is a long a highly political process.  For example
the farmers were ordered to reduce runoff 20 years ago and every year they
are granted a one year waiver.

Back to the point.  We periodically measure a number of analytes and my
main interests are in learning whether the water quality is improving or
not, and predicting what may happen during worst case times.  So
statistical analysis of the SWAMP data is where I may be able to help.  I
am not a biologist or water scientist,  but I do have a reasonable grasp of
statistics and charting.

I was going to take your R6-water-quality code and update it to use CKAN
API's to pull data within our harbor and display it, but I came across your
new dashboard and I am sure it will be what we need.   I have a number of
suggestions for enhancements, but since I do not know what your goals or
schedule is I didn't want to dump them on you.

For us, the most useful enhancement would be to use color or some other
visual cue to denote whether various measurements were improving or
degrading over time and to highlight any exceedances of TMDL's.  For
example a tiny line chart by each point on the map display with green/red
lines.  I really appreciate your work and it is very useful just as it is.
My real problem is getting all of our data into CEDEN which has been
another challenge.  The city has engaged the various labs we use to do
that, but somehow they are not doing it.

Thanks and regards,

**Comment by mmtang** [comment]
Thanks for sharing! It is helpful for me and for all of us at SWAMP to know what the potential use cases for this app are. I'll keep this issue open until I can follow up with some next steps.

**Comment by mmtang** [comment]
Hi @j0el, just a quick update. The next release has been delayed because of a data issue. I can't give an estimate for when this issue will be resolved (hopefully soon), but I'll reach out again when we're ready for testing. Thanks again for your patience and your interest in this project!

**Comment by j0el** [comment]
Thanks for the update.  If there is anything i can help with please let me
know.

**Comment by mmtang** [comment]
Closing - will continue via email
